# git-cliff configuration
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog 1.1.0](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
body = """
{%- if version %}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{%- else %}
## [Unreleased]
{%- endif %}
{%- for group, commits in commits | group_by(attribute="group") %}

### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | split(pat=": ") | last | upper_first | trim }}.
{%- endfor %}
{%- endfor %}

"""
trim = true

[git]
conventional_commits = false
filter_commits = true
filter_unconventional = false
split_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
sort_commits = "oldest"

commit_preprocessors = [
    { pattern = "Co-authored-by:.*", replace = "" },
]

commit_parsers = [
    { message = "^Merge", skip = true },
    { message = "^chore: update changelog", skip = true },
    { message = "^wip$", skip = true },
    { message = "^WIP$", skip = true },
    { message = "^(task|todo)(:|\\()", skip = true },
    { message = ": add ", group = "Added" },
    { message = ": scaffold", group = "Added" },
    { message = ": implement", group = "Added" },
    { message = ": create", group = "Added" },
    { message = ": document", group = "Added" },
    { message = ": fix", group = "Fixed" },
    { message = ": correct", group = "Fixed" },
    { message = ": update", group = "Changed" },
    { message = ": refactor", group = "Changed" },
    { message = ": standardize", group = "Changed" },
    { message = ": rename", group = "Changed" },
    { message = ": replace", group = "Changed" },
    { message = ": clarify", group = "Changed" },
    { message = ": link", group = "Changed" },
    { message = ": remove", group = "Removed" },
    { message = ": delete", group = "Removed" },
    { message = ": deprecate", group = "Deprecated" },
    { message = ": security", group = "Security" },
    { message = "^.*", group = "Other" },
]
